version: '3.4'

services:

  api:
    container_name: springmongodb
    image: ${DOCKER_REGISTRY-}springmongodb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8080

  mongo:
    container_name: bookstoredb
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
